/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreaComercialRouteImport } from './routes/area-comercial'
import { Route as AreaMedicoRouteImport } from './routes/area-medico'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as MedicosRouteImport } from './routes/medicos'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as OrcamentosIndexRouteImport } from './routes/orcamentos/index'
import { Route as OrcamentosIdRouteImport } from './routes/orcamentos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaComercialRoute = AreaComercialRouteImport.update({
  id: '/area-comercial',
  path: '/area-comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaMedicoRoute = AreaMedicoRouteImport.update({
  id: '/area-medico',
  path: '/area-medico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicosRoute = MedicosRouteImport.update({
  id: '/medicos',
  path: '/medicos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIndexRoute = OrcamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrcamentosRoute,
} as any)
const OrcamentosIdRoute = OrcamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrcamentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-comercial': typeof AreaComercialRoute
  '/area-medico': typeof AreaMedicoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/medicos': typeof MedicosRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-comercial': typeof AreaComercialRoute
  '/area-medico': typeof AreaMedicoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/medicos': typeof MedicosRoute
  '/usuarios': typeof UsuariosRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos': typeof OrcamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-comercial': typeof AreaComercialRoute
  '/area-medico': typeof AreaMedicoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/medicos': typeof MedicosRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/usuarios': typeof UsuariosRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/area-comercial'
    | '/area-medico'
    | '/configuracoes'
    | '/medicos'
    | '/orcamentos'
    | '/usuarios'
    | '/orcamentos/$id'
    | '/orcamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/area-comercial'
    | '/area-medico'
    | '/configuracoes'
    | '/medicos'
    | '/usuarios'
    | '/orcamentos/$id'
    | '/orcamentos'
  id:
    | '__root__'
    | '/'
    | '/area-comercial'
    | '/area-medico'
    | '/configuracoes'
    | '/medicos'
    | '/orcamentos'
    | '/usuarios'
    | '/orcamentos/$id'
    | '/orcamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaComercialRoute: typeof AreaComercialRoute
  AreaMedicoRoute: typeof AreaMedicoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  MedicosRoute: typeof MedicosRoute
  OrcamentosRoute: typeof OrcamentosRouteWithChildren
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-comercial': {
      id: '/area-comercial'
      path: '/area-comercial'
      fullPath: '/area-comercial'
      preLoaderRoute: typeof AreaComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-medico': {
      id: '/area-medico'
      path: '/area-medico'
      fullPath: '/area-medico'
      preLoaderRoute: typeof AreaMedicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicos': {
      id: '/medicos'
      path: '/medicos'
      fullPath: '/medicos'
      preLoaderRoute: typeof MedicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/': {
      id: '/orcamentos/'
      path: '/'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof OrcamentosIndexRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/orcamentos/$id': {
      id: '/orcamentos/$id'
      path: '/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof OrcamentosIdRouteImport
      parentRoute: typeof OrcamentosRoute
    }
  }
}

interface OrcamentosRouteChildren {
  OrcamentosIdRoute: typeof OrcamentosIdRoute
  OrcamentosIndexRoute: typeof OrcamentosIndexRoute
}

const OrcamentosRouteChildren: OrcamentosRouteChildren = {
  OrcamentosIdRoute: OrcamentosIdRoute,
  OrcamentosIndexRoute: OrcamentosIndexRoute,
}

const OrcamentosRouteWithChildren = OrcamentosRoute._addFileChildren(
  OrcamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaComercialRoute: AreaComercialRoute,
  AreaMedicoRoute: AreaMedicoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  MedicosRoute: MedicosRoute,
  OrcamentosRoute: OrcamentosRouteWithChildren,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
